#!/usr/bin/zsh -i

function nice-alias() {

	array_of_aliases=("${(@f)$(alias)//\'}")
	for iter in $array_of_aliases
	do
		IFS='=' read -r al cmd <<< $iter
		print -P '%B%F{red}$al%F{green} = %F{blue}$cmd%f%b'
	done



}

nice-alias "$@"
