#!/usr/bin/env bash
keyid=5686D0EBC96E9B54CC5F3367B198DAAB514B53CF
gpgconf --kill gpg-agent
cd "$(gpgconf --list-dirs homedir)/private-keys-v1.d"
gpg -K --with-keygrip --with-colons "$keyid" | \
awk -F: '/^grp/ { print $10".key"; }' | \
xargs rm -vf
